// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: kvStore.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpKeyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpKeyReq) Reset() {
	*x = OpKeyReq{}
	mi := &file_kvStore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpKeyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpKeyReq) ProtoMessage() {}

func (x *OpKeyReq) ProtoReflect() protoreflect.Message {
	mi := &file_kvStore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpKeyReq.ProtoReflect.Descriptor instead.
func (*OpKeyReq) Descriptor() ([]byte, []int) {
	return file_kvStore_proto_rawDescGZIP(), []int{0}
}

func (x *OpKeyReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type SetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetReq) Reset() {
	*x = SetReq{}
	mi := &file_kvStore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetReq) ProtoMessage() {}

func (x *SetReq) ProtoReflect() protoreflect.Message {
	mi := &file_kvStore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetReq.ProtoReflect.Descriptor instead.
func (*SetReq) Descriptor() ([]byte, []int) {
	return file_kvStore_proto_rawDescGZIP(), []int{1}
}

func (x *SetReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetReq) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type OpRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpRes) Reset() {
	*x = OpRes{}
	mi := &file_kvStore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpRes) ProtoMessage() {}

func (x *OpRes) ProtoReflect() protoreflect.Message {
	mi := &file_kvStore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpRes.ProtoReflect.Descriptor instead.
func (*OpRes) Descriptor() ([]byte, []int) {
	return file_kvStore_proto_rawDescGZIP(), []int{2}
}

type OpGetRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpGetRes) Reset() {
	*x = OpGetRes{}
	mi := &file_kvStore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpGetRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpGetRes) ProtoMessage() {}

func (x *OpGetRes) ProtoReflect() protoreflect.Message {
	mi := &file_kvStore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpGetRes.ProtoReflect.Descriptor instead.
func (*OpGetRes) Descriptor() ([]byte, []int) {
	return file_kvStore_proto_rawDescGZIP(), []int{3}
}

func (x *OpGetRes) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_kvStore_proto protoreflect.FileDescriptor

const file_kvStore_proto_rawDesc = "" +
	"\n" +
	"\rkvStore.proto\x12\akvStore\"\x1c\n" +
	"\bopKeyReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"0\n" +
	"\x06setReq\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\a\n" +
	"\x05opRes\" \n" +
	"\bopGetRes\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value2\x97\x01\n" +
	"\akvstore\x120\n" +
	"\x06kv_get\x12\x11.kvStore.opKeyReq\x1a\x11.kvStore.opGetRes\"\x00\x12+\n" +
	"\x06kv_set\x12\x0f.kvStore.setReq\x1a\x0e.kvStore.opRes\"\x00\x12-\n" +
	"\x06kv_del\x12\x11.kvStore.opKeyReq\x1a\x0e.kvStore.opRes\"\x00B\x03Z\x01.b\x06proto3"

var (
	file_kvStore_proto_rawDescOnce sync.Once
	file_kvStore_proto_rawDescData []byte
)

func file_kvStore_proto_rawDescGZIP() []byte {
	file_kvStore_proto_rawDescOnce.Do(func() {
		file_kvStore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kvStore_proto_rawDesc), len(file_kvStore_proto_rawDesc)))
	})
	return file_kvStore_proto_rawDescData
}

var file_kvStore_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_kvStore_proto_goTypes = []any{
	(*OpKeyReq)(nil), // 0: kvStore.opKeyReq
	(*SetReq)(nil),   // 1: kvStore.setReq
	(*OpRes)(nil),    // 2: kvStore.opRes
	(*OpGetRes)(nil), // 3: kvStore.opGetRes
}
var file_kvStore_proto_depIdxs = []int32{
	0, // 0: kvStore.kvstore.kv_get:input_type -> kvStore.opKeyReq
	1, // 1: kvStore.kvstore.kv_set:input_type -> kvStore.setReq
	0, // 2: kvStore.kvstore.kv_del:input_type -> kvStore.opKeyReq
	3, // 3: kvStore.kvstore.kv_get:output_type -> kvStore.opGetRes
	2, // 4: kvStore.kvstore.kv_set:output_type -> kvStore.opRes
	2, // 5: kvStore.kvstore.kv_del:output_type -> kvStore.opRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kvStore_proto_init() }
func file_kvStore_proto_init() {
	if File_kvStore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kvStore_proto_rawDesc), len(file_kvStore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kvStore_proto_goTypes,
		DependencyIndexes: file_kvStore_proto_depIdxs,
		MessageInfos:      file_kvStore_proto_msgTypes,
	}.Build()
	File_kvStore_proto = out.File
	file_kvStore_proto_goTypes = nil
	file_kvStore_proto_depIdxs = nil
}
