// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: kvStore.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Kvstore_KvGet_FullMethodName = "/kvStore.kvstore/kv_get"
	Kvstore_KvSet_FullMethodName = "/kvStore.kvstore/kv_set"
	Kvstore_KvDel_FullMethodName = "/kvStore.kvstore/kv_del"
)

// KvstoreClient is the client API for Kvstore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KvstoreClient interface {
	KvGet(ctx context.Context, in *OpKeyReq, opts ...grpc.CallOption) (*OpGetRes, error)
	KvSet(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*OpRes, error)
	KvDel(ctx context.Context, in *OpKeyReq, opts ...grpc.CallOption) (*OpRes, error)
}

type kvstoreClient struct {
	cc grpc.ClientConnInterface
}

func NewKvstoreClient(cc grpc.ClientConnInterface) KvstoreClient {
	return &kvstoreClient{cc}
}

func (c *kvstoreClient) KvGet(ctx context.Context, in *OpKeyReq, opts ...grpc.CallOption) (*OpGetRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpGetRes)
	err := c.cc.Invoke(ctx, Kvstore_KvGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvstoreClient) KvSet(ctx context.Context, in *SetReq, opts ...grpc.CallOption) (*OpRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpRes)
	err := c.cc.Invoke(ctx, Kvstore_KvSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvstoreClient) KvDel(ctx context.Context, in *OpKeyReq, opts ...grpc.CallOption) (*OpRes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpRes)
	err := c.cc.Invoke(ctx, Kvstore_KvDel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvstoreServer is the server API for Kvstore service.
// All implementations must embed UnimplementedKvstoreServer
// for forward compatibility.
type KvstoreServer interface {
	KvGet(context.Context, *OpKeyReq) (*OpGetRes, error)
	KvSet(context.Context, *SetReq) (*OpRes, error)
	KvDel(context.Context, *OpKeyReq) (*OpRes, error)
	mustEmbedUnimplementedKvstoreServer()
}

// UnimplementedKvstoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKvstoreServer struct{}

func (UnimplementedKvstoreServer) KvGet(context.Context, *OpKeyReq) (*OpGetRes, error) {
	return nil, status.Error(codes.Unimplemented, "method KvGet not implemented")
}
func (UnimplementedKvstoreServer) KvSet(context.Context, *SetReq) (*OpRes, error) {
	return nil, status.Error(codes.Unimplemented, "method KvSet not implemented")
}
func (UnimplementedKvstoreServer) KvDel(context.Context, *OpKeyReq) (*OpRes, error) {
	return nil, status.Error(codes.Unimplemented, "method KvDel not implemented")
}
func (UnimplementedKvstoreServer) mustEmbedUnimplementedKvstoreServer() {}
func (UnimplementedKvstoreServer) testEmbeddedByValue()                 {}

// UnsafeKvstoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KvstoreServer will
// result in compilation errors.
type UnsafeKvstoreServer interface {
	mustEmbedUnimplementedKvstoreServer()
}

func RegisterKvstoreServer(s grpc.ServiceRegistrar, srv KvstoreServer) {
	// If the following call panics, it indicates UnimplementedKvstoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Kvstore_ServiceDesc, srv)
}

func _Kvstore_KvGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvstoreServer).KvGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kvstore_KvGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvstoreServer).KvGet(ctx, req.(*OpKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvstore_KvSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvstoreServer).KvSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kvstore_KvSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvstoreServer).KvSet(ctx, req.(*SetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Kvstore_KvDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvstoreServer).KvDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Kvstore_KvDel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvstoreServer).KvDel(ctx, req.(*OpKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Kvstore_ServiceDesc is the grpc.ServiceDesc for Kvstore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Kvstore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kvStore.kvstore",
	HandlerType: (*KvstoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "kv_get",
			Handler:    _Kvstore_KvGet_Handler,
		},
		{
			MethodName: "kv_set",
			Handler:    _Kvstore_KvSet_Handler,
		},
		{
			MethodName: "kv_del",
			Handler:    _Kvstore_KvDel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kvStore.proto",
}
